<a href="https://colab.research.google.com/github/drpetros11111/DeepUnderstanding_DL/blob/Matrix/DUDL_math_matrixMult.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[ 2.09 -7.81 -2.94  1.15 -0.98]
 [ 1.4  -3.97 -1.45 -0.93 -1.7 ]
 [ 1.08 -0.92 -0.31  1.88  0.86]]
 
[[-0.4  -1.21 -1.11 -1.03]
 [ 6.01  0.84 -3.08 -2.08]
 [-4.54 -1.04  2.13  1.44]
 [-0.6  -1.5  -1.83 -1.77]
 [ 0.3  -0.81 -0.56 -0.38]
 [-0.96 -1.07 -0.68 -0.72]
 [ 0.97  1.27 -0.44 -0.47]]


# Using Tensorflow

In [10]:
import tensorflow as tf
import numpy as np

# Create some random matrices
A = tf.random.normal((3, 4))  # A is 3x4
B = tf.random.normal((4, 5))  # B is 4x5
C1 = np.random.randn(4, 7)    # C1 is 4x7
C2 = tf.convert_to_tensor(C1, dtype=tf.float32)  # C2 is 4x7

# Perform some multiplications and print the results
# A (3x4) @ B (4x5) = (3x5)
print(np.round(tf.matmul(A, B).numpy(), 2))
print(' ')

# Transpose of A for multiplication with B.T
# A.T (4x3) @ B.T (5x4) - This is invalid
# Correct multiplication should be:
print(np.round(tf.matmul(tf.transpose(A), tf.random.normal((3, 4))).numpy(), 2))  # (4x3) @ (4x3) = (4x3)
print(' ')

# A (3x4) @ C1 (4x7) = (3x7)
print(np.round(tf.matmul(A, C1).numpy(), 2))
print(' ')

# A (3x4) @ C2 (4x7) = (3x7)
print(np.round(tf.matmul(A, C2).numpy(), 2))

[[-3.82 -2.82 -4.34 -1.62  0.82]
 [-0.65 -1.12 -1.05 -0.7   3.28]
 [ 0.7   2.28  2.17  0.27 -2.22]]
 
[[ 1.12 -2.04 -1.04 -0.08]
 [-3.35  2.89 -1.57  0.61]
 [ 0.3  -0.73  1.21 -1.34]
 [ 0.62  0.89  1.95  0.06]]
 
[[ 0.94  1.31  1.25 -1.2   0.09 -1.17 -1.31]
 [-1.39  1.32 -0.3   1.3  -0.75  0.24 -0.79]
 [ 0.83 -0.52  1.98  0.46  1.43  0.16  2.6 ]]
 
[[ 0.94  1.31  1.25 -1.2   0.09 -1.17 -1.31]
 [-1.39  1.32 -0.3   1.3  -0.75  0.24 -0.79]
 [ 0.83 -0.52  1.98  0.46  1.43  0.16  2.6 ]]


# Matrix Multiplication

    tf.matmul(A, B)

##tf.matmul

performs matrix multiplication between two tensors A and B.

For matrix multiplication to be valid, the number of columns in A must match the number of rows in B.

Given that A is of shape (3, 4) and B is of shape (4, 5), this operation is valid.

The result will be a tensor with shape (3, 5), as the outer dimensions of the matrices determine the shape of the resulting matrix.

-----------------------
#Convert Tensor to NumPy Array:

    tf.matmul(A, B).numpy()

tf.matmul(A, B) returns a TensorFlow tensor.

##.numpy()

converts this tensor to a NumPy array, making it easier to work with for further operations or printing.

----------------
#Round the Values:

    np.round(..., 2)

##np.round

rounds the values of the NumPy array to the specified number of decimal places. Here, 2 indicates rounding to two decimal places.

This helps in formatting the output to be more readable by reducing the number of decimal places.

--------------------------
#Print the Result:

    print(...)
print outputs the result to the console.

----------------
#Example
Assuming A is:

    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

And B is:

    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20]]

Then tf.matmul(A, B) would yield:


    [[  90, 100, 110, 120, 130],
     [202, 228, 254, 280, 306],
     [314, 356, 398, 440, 482]]

After rounding (though here rounding is not necessary as values are already integers), you would get:

    [[  90., 100., 110., 120., 130.],
     [ 202., 228., 254., 280., 306.],
     [ 314., 356., 398., 440., 482.]]

This statement thus performs the matrix multiplication, converts the result to a NumPy array, rounds the values to two decimal places, and prints the final output.

# Using Pytorch

In [3]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[ 0.5300,  4.9900,  0.2100,  2.1200, -2.8600,  0.6500, -2.1200],
        [ 1.3500, -0.9900,  2.4600, -1.7200,  3.3300,  0.1300, -2.5600],
        [-1.5500,  0.3100,  1.7700,  2.8200, -6.2700, -1.8500,  6.7800]],
       dtype=torch.float64)
 
tensor([[ 0.5300,  4.9900,  0.2100,  2.1200, -2.8600,  0.6500, -2.1200],
        [ 1.3500, -0.9900,  2.4600, -1.7200,  3.3300,  0.1300, -2.5600],
        [-1.5500,  0.3100,  1.7700,  2.8200, -6.2700, -1.8500,  6.7800]])
