<a href="https://colab.research.google.com/github/drpetros11111/DeepUnderstanding_DL/blob/Math/DUDL_math_randomseed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Identical randomness via seeding
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401

In [1]:
# import libraries
import numpy as np
import torch

In [2]:
# generate a few random numbers
np.random.randn(5)

array([1.38431608, 0.15455336, 0.43882593, 1.52470505, 0.20424841])

In [4]:
# repeat after fixing the seed (old-but-still-widely-used method)
np.random.seed(17)
print(np.random.randn(5))
print(np.random.randn(5))

# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


# New seed mechanism in numpy

In [7]:
randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(20210530)

print( randseed1.randn(5) ) # same sequence
print( randseed2.randn(5) ) # different from above, but same each time
print( randseed1.randn(5) ) # same as two up
print( randseed2.randn(5) ) # same as two up
print( np.random.randn(5) ) # different every time

# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
# [ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
# [ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
[-0.9822943   1.03126909  0.49133378 -0.4466466  -0.80636008]


# Random State Key Concepts
--------------
## RandomState:

This is an object used to create a new instance of a random number generator.

By setting a seed, you can ensure that the random numbers generated are reproducible.

Different instances of RandomState with different seeds will generate different sequences of random numbers.

-----------------------
#randn():

This function generates random numbers from a standard normal distribution (mean 0, standard deviation 1).

The numbers are drawn from this distribution.

-----------------------
-------------------------
#Code Breakdown:

    randseed1 = np.random.RandomState(17)
    randseed2 = np.random.RandomState(20210530)

Here, two random number generators (randseed1 and randseed2) are created with different seeds (17 and 20210530).

These seeds determine the sequence of random numbers that will be generated by each random number generator.


##Random Number Generation:

    print(randseed1.randn(5))  # same sequence

This generates 5 random numbers from randseed1, which is based on the seed 17.

Each time you run the code, the same sequence of numbers will be generated from this seed.

    print(randseed2.randn(5))  # different from above, but same each time

This generates 5 random numbers from randseed2, based on the seed 20210530.

These numbers will be different from the ones generated by randseed1 but will always be the same for this specific seed.

    print(randseed1.randn(5))  # same as two up

This generates another 5 random numbers from randseed1.

Since this random generator was already used once, the new numbers are part of the sequence generated from seed 17.

It’s the continuation of the sequence, so these numbers will always be the same every time you run this line of code.

    print(randseed2.randn(5))  # same as two up

This generates another 5 random numbers from randseed2, again following the continuation of the sequence from seed 20210530.

Like before, the numbers will always be the same for this specific seed.

    print(np.random.randn(5))  # different every time

This generates 5 random numbers using np.random.randn(5), which does not use a specific seed.

As a result, this will produce different random numbers each time you run the code because no seed was set.

------------------
#Summary
randseed1 and randseed2 are reproducible because they are initialized with specific seeds (17 and 20210530), ensuring that the random number sequences are the same each time you run the code.

Without setting a seed (np.random.randn(5)), the random numbers change every time the code is executed.

[-1.77528229  1.31487654 -0.47344805 -1.0922299  -0.25002744]


# Now in pytorch

In [8]:
torch.randn(5)

tensor([ 0.4042,  0.6359, -0.6229,  0.2103,  0.3948])

In [9]:
torch.manual_seed(17)
print( torch.randn(5) )

# torch's seed doesn't spread to numpy
print( np.random.randn(5) )

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[ 0.13126776 -1.21256024  0.15999085 -0.75522304  0.34989599]
