<a href="https://colab.research.google.com/github/drpetros11111/DeepUnderstanding_DL/blob/Matrix/DUDL_math_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Vector and matrix transpose
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create a vector
nv = np.array([ [1,2,3,4] ])
print(nv), print(' ')

# transpose it
print(nv.T), print(' ')

# transpose the transpose!
nvT = nv.T
print(nvT.T)

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


In [3]:
# repeat for a matrix
nM = np.array([ [1,2,3,4],
                [5,6,7,8]
               ])
print(nM), print(' ')

# transpose it
print(nM.T), print(' ')

# transpose the transpose!
nMT = nM.T
print(nMT.T)

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]


# Using pytorch

In [ ]:
# create a vector
tv = torch.tensor([ [1,2,3,4] ])
print(tv), print(' ')

# transpose it
print(tv.T), print(' ')

# transpose the transpose!
tvT = tv.T
print(tvT.T)

# TENSOR FLOW

In [4]:
import tensorflow as tf

# Create a vector
tv = tf.constant([[1, 2, 3, 4]])
print(tv.numpy())
print(' ')

# Transpose it
tv_T = tf.transpose(tv)
print(tv_T.numpy())
print(' ')

# Transpose the transpose!
tv_T_T = tf.transpose(tv_T)
print(tv_T_T.numpy())


[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


# Creating the Tensor in TF

--------------------
    tv = tf.constant([[1, 2, 3, 4]])
    tf.constant creates a TensorFlow tensor with the given data.

##[[1, 2, 3, 4]]

is a 2D list (a list of lists) where the inner list represents a row in a matrix. In this case, there is only one row, so the tensor is a 1x4 matrix (or vector) with the values [1, 2, 3, 4].

---------------
##Printing the Tensor:

    print(tv.numpy())
    tv.numpy() converts the TensorFlow tensor to a NumPy array so it can be printed in a readable format.
    print(tv.numpy()) outputs the tensor's values. For this example, it will print [[1 2 3 4]], which is the 1x4 tensor.

##Printing a Blank Line:

    print(' ')
This simply prints an empty line to separate outputs visually.
Overall, this snippet creates a 1x4 tensor and prints it out as a NumPy array, followed by a blank line for formatting.

# PyTorch

In [8]:
# repeat for a matrix
tM = torch.tensor([ [1,2,3,4],[5,6,7,8] ])
print(tM), print(' ')

# transpose it
print(tM.T), print(' ')

# transpose the transpose!
tMT = tM.T
print(tMT.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [7]:
# examine data types
print(f'Variable nv is of type {type(nv)}')
print(f'Variable nM is of type {type(nM)}')
print(f'Variable tv is of type {type(tv)}')

# Ensure that the code that defines tM has been executed in the current scope
import torch
tM = torch.tensor([ [1,2,3,4],[5,6,7,8] ])
print(f'Variable tM is of type {type(tM)}')

Variable nv is of type <class 'numpy.ndarray'>
Variable nM is of type <class 'numpy.ndarray'>
Variable tv is of type <class 'tensorflow.python.framework.ops.EagerTensor'>
Variable tM is of type <class 'torch.Tensor'>
